#!/bin/sh

# zx_repalce
# Brief: Replace all occurrences of a string in a file.
# Usage: replace <string> <replacement> <file>
# =======
zx_replace() {
    if [[ "$OSTYPE" == darwin* ]]; then
        sed -i "" "s+$1+$2+g" `grep -rl $1 $3`
    else
        sed -i "s+$1+$2+g" `grep -rl $1 $3`
    fi
}

zx_replace "$@"